<a href="https://colab.research.google.com/github/Rumana0612/Bird-Strikes-between-2000-2011/blob/main/BirdStrikes.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:

import pandas as pd
import seaborn as sns

In [ ]:
df=pd.read_csv('Bird Strikes data.csv')

In [ ]:
df.shape

(25558, 26)

In [ ]:
df.head(4)

,Record ID,Aircraft: Type,Airport: Name,Altitude bin,Aircraft: Make/Model,Wildlife: Number struck,Wildlife: Number Struck Actual,Effect: Impact to flight,FlightDate,Effect: Indicated Damage,...,Remains of wildlife sent to Smithsonian,Remarks,Wildlife: Size,Conditions: Sky,Wildlife: Species,Pilot warned of birds or wildlife?,Cost: Total $,Feet above ground,Number of people injured,Is Aircraft Large?
0,202152,Airplane,LAGUARDIA NY,> 1000 ft,B-737-400,Over 100,859,Engine Shut Down,11/23/2000 0:00,Caused damage,...,False,FLT 753. PILOT REPTD A HUNDRED BIRDS ON UNKN T...,Medium,No Cloud,Unknown bird - medium,N,"30,736","1,500",0,Yes
1,208159,Airplane,DALLAS/FORT WORTH INTL ARPT,< 1000 ft,MD-80,Over 100,424,NaN,7/25/2001 0:00,Caused damage,...,False,102 CARCASSES FOUND. 1 LDG LIGHT ON NOSE GEAR ...,Small,Some Cloud,Rock pigeon,Y,0,0,0,No
2,207601,Airplane,LAKEFRONT AIRPORT,< 1000 ft,C-500,Over 100,261,NaN,9/14/2001 0:00,No damage,...,False,FLEW UNDER A VERY LARGE FLOCK OF BIRDS OVER AP...,Small,No Cloud,European starling,N,0,50,0,No
3,215953,Airplane,SEATTLE-TACOMA INTL,< 1000 ft,B-737-400,Over 100,806,Precautionary Landing,9/5/2002 0:00,No damage,...,False,"NOTAM WARNING. 26 BIRDS HIT THE A/C, FORCING A...",Small,Some Cloud,European starling,Y,0,50,0,Yes

In [ ]:
print(df.dtypes)

Record ID                                   int64
Aircraft: Type                             object
Airport: Name                              object
Altitude bin                               object
Aircraft: Make/Model                       object
Wildlife: Number struck                    object
Wildlife: Number Struck Actual              int64
Effect: Impact to flight                   object
FlightDate                                 object
Effect: Indicated Damage                   object
Aircraft: Number of engines?               object
Aircraft: Airline/Operator                 object
Origin State                               object
When: Phase of flight                      object
Conditions: Precipitation                  object
Remains of wildlife collected?               bool
Remains of wildlife sent to Smithsonian      bool
Remarks                                    object
Wildlife: Size                             object
Conditions: Sky                            object
Wildlife: Species                          object
Pilot warned of birds or wildlife?         object
Cost: Total $                              object
Feet above ground                          object
Number of people injured                    int64
Is Aircraft Large?                         object
dtype: object

In [ ]:
df=df.drop(columns=['Remarks','Conditions: Sky','Conditions: Precipitation'])
print(df.columns)

Index(['Record ID', 'Aircraft: Type', 'Airport: Name', 'Altitude bin',
       'Aircraft: Make/Model', 'Wildlife: Number struck',
       'Wildlife: Number Struck Actual', 'Effect: Impact to flight',
       'FlightDate', 'Effect: Indicated Damage',
       'Aircraft: Number of engines?', 'Aircraft: Airline/Operator',
       'Origin State', 'When: Phase of flight',
       'Remains of wildlife collected?',
       'Remains of wildlife sent to Smithsonian', 'Wildlife: Size',
       'Wildlife: Species', 'Pilot warned of birds or wildlife?',
       'Cost: Total $', 'Feet above ground', 'Number of people injured',
       'Is Aircraft Large?'],
      dtype='object')

In [ ]:
df.rename(columns={'Wildlife: Number Struck Actual ':'Wildlife struck','Aircraft: Make/Model':'Model'},inplace=True)

In [ ]:
df.drop_duplicates()

,Record ID,Aircraft: Type,Airport: Name,Altitude bin,Model,Wildlife: Number struck,Wildlife: Number Struck Actual,Effect: Impact to flight,FlightDate,Effect: Indicated Damage,...,When: Phase of flight,Remains of wildlife collected?,Remains of wildlife sent to Smithsonian,Wildlife: Size,Wildlife: Species,Pilot warned of birds or wildlife?,Cost: Total $,Feet above ground,Number of people injured,Is Aircraft Large?
0,202152,Airplane,LAGUARDIA NY,> 1000 ft,B-737-400,Over 100,859,Engine Shut Down,11/23/2000 0:00,Caused damage,...,Climb,False,False,Medium,Unknown bird - medium,N,"30,736","1,500",0,Yes
1,208159,Airplane,DALLAS/FORT WORTH INTL ARPT,< 1000 ft,MD-80,Over 100,424,NaN,7/25/2001 0:00,Caused damage,...,Landing Roll,False,False,Small,Rock pigeon,Y,0,0,0,No
2,207601,Airplane,LAKEFRONT AIRPORT,< 1000 ft,C-500,Over 100,261,NaN,9/14/2001 0:00,No damage,...,Approach,False,False,Small,European starling,N,0,50,0,No
3,215953,Airplane,SEATTLE-TACOMA INTL,< 1000 ft,B-737-400,Over 100,806,Precautionary Landing,9/5/2002 0:00,No damage,...,Climb,True,False,Small,European starling,Y,0,50,0,Yes
4,219878,Airplane,NORFOLK INTL,< 1000 ft,CL-RJ100/200,Over 100,942,NaN,6/23/2003 0:00,No damage,...,Approach,False,False,Small,European starling,N,0,50,0,No
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
25553,321151,Airplane,REDDING MUNICIPAL,> 1000 ft,EMB-120,1,1,NaN,12/30/2011 0:00,No damage,...,Approach,False,False,Large,Unknown bird - large,N,0,"1,500",0,No
25554,319677,Airplane,ORLANDO INTL,< 1000 ft,A-321,1,1,NaN,12/30/2011 0:00,No damage,...,Landing Roll,False,False,Small,Tree swallow,Y,0,0,0,No
25555,319680,NaN,NaN,NaN,EC-135,NaN,1,NaN,NaN,No damage,...,NaN,False,False,NaN,Unknown bird - small,NaN,0,NaN,0,NaN
25556,319679,Airplane,DETROIT METRO WAYNE COUNTY ARPT,< 1000 ft,B-757-200,1,1,NaN,12/31/2011 0:00,No damage,...,Landing Roll,False,False,Medium,Unknown bird - medium,Y,0,0,0,Yes
25557,319593,Airplane,ABRAHAM LINCOLN CAPITAL ARPT,< 1000 ft,B-737-400,1,1,NaN,12/31/2011 0:00,Caused damage,...,Take-off run,True,False,Medium,Red-tailed hawk,N,0,0,0,Yes

In [ ]:
df.isnull().sum()

Record ID                                      0
Aircraft: Type                               129
Airport: Name                                129
Altitude bin                                 129
Model                                          0
Wildlife: Number struck                      129
Wildlife: Number Struck Actual                 0
Effect: Impact to flight                   23480
FlightDate                                   129
Effect: Indicated Damage                       0
Aircraft: Number of engines?                 267
Aircraft: Airline/Operator                   129
Origin State                                 449
When: Phase of flight                        129
Remains of wildlife collected?                 0
Remains of wildlife sent to Smithsonian        0
Wildlife: Size                               129
Wildlife: Species                              0
Pilot warned of birds or wildlife?           129
Cost: Total $                                  0
Feet above ground                            129
Number of people injured                       0
Is Aircraft Large?                           129
dtype: int64

In [ ]:
df=df.dropna()
df.isnull().sum()
df.shape

(1995, 23)

In [ ]:
df.to_excel('Bird strick.xlsx')